### ISSUE TITLE
Dependency to Insee internal configuration component

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/ARC#1]
It is written as an outstanding warning in the documentation : there is a dependency to an INSEE internal java component for ARC. This link make the whole application not usable.

When a solution will be provided ?

**Comment by Nolife999** [comment]
Hello,
A solution will be provided very soon. The INSEE internal java configuration had already been replaced by the SPRING property placeholder implementation in the web and the core modules and it had been tested successfully.

**Comment by HealerMikado** [comment]
Indeed it work, but there are some problems with the log configuration :'(

**Comment by Nolife999** [comment]
Lacking implementation on the batch and web service modules.Web and core modules had been fixed. The web application can work out of the INSEE environment from now on.

**Comment by pierre-le-corre** [comment]
Done by @Nolife999 with the PropertiesHandler class.
