### ISSUE TITLE
Reorganising the documentation

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/ARC#2]
The main documentation (provided through the [README.md](https://github.com/InseeFr/ARC/blob/master/README.md)) is useful but maybe a bit dense for a first grip on what ARC is about.

Identically to what is generally provided by open-source software (1), we may provide a first README that would :

- provide a quick context paragraph
- how to run the application
- a link to more documentation (the existing README file for example)
- how to interact with the maintainers and contribute

(1) see for example the [tensorflow github repo](https://github.com/tensorflow/tensorflow) or the one for [airflow](https://github.com/apache/airflow)

**Comment by HealerMikado** [comment]
The README was made in a hurry, will update it newt week =)

**Comment by romaintailhurat** [comment]
Nice, thank you Rémi.

**Comment by HealerMikado** [comment]
First update of the doc in #14

**Comment by Nolife999** [comment]
Closing. It looks good now
