### ISSUE TITLE
BiUntokenizer interface not used

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/ARC#24]
My IDE tell me that [BiUntokenizer](https://github.com/InseeFr/ARC/blob/master/arc-utils/src/main/java/fr/insee/arc/utils/textUtils/BiUntokenizer.java) is never used.

Is it dead code or work-in-progress ? In the first case, we should remove the interface, shouldn't we ?

**Comment by Nolife999** [comment]
Yes Romain, it can be removed. The reason is that the "arc-util" project is a refactor of our internal "siera" project which groups up utility voids and functions that are used by ARC and also by the other softwares of our information system.

**Comment by Nolife999** [comment]
I will be able to take care of that the 20/09. If you want to do it before Romain, go ahead :)
