### ISSUE TITLE
Use classes or enums not interfaces for storing constants

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/ARC#25]
In the textUtils package, three interfaces hold various constants (see for example [IConstanteCaractere](https://github.com/InseeFr/ARC/blob/master/arc-utils/src/main/java/fr/insee/arc/utils/textUtils/IConstanteCaractere.java)).

Why don't we simply use classes for that ? Or best, enums (see [that post](https://stackoverflow.com/questions/66066/what-is-the-best-way-to-implement-constants-in-java) for reference) ! :sparkles:

**Comment by romaintailhurat** [comment]
After discussing the issue with @NoLife999 i'll transform the interfaces to enums.

**Comment by romaintailhurat** [comment]
Oh, this one is tougher than i previously thought! :grimacing: 

14 classes are extending one or several of those interfaces (see [this ](https://github.com/InseeFr/ARC/blob/master/arc-core/src/main/java/fr/insee/arc/core/service/mapping/RequeteMapping.java) or [that ](https://github.com/InseeFr/ARC/blob/master/arc-utils/src/main/java/fr/insee/arc/utils/bdd/AbstractRequeteSQLCalibree.java)for example).

Maybe it is too much of an hassle to refactor to enum ? It implies now to redesign those 14 classes. :hushed:

**Comment by HealerMikado** [comment]
2 month ago I tried to refactor those interfaces, but was indeed too much of an hassle to refactor to enum T_T

**Comment by romaintailhurat** [comment]
Yes.

I'll let @NoLife999 decide if it's worth it. If not, i'll resume my work on translation i guess. Or architecture.

**Comment by Nolife999** [comment]
I vote to let it be for now :)

**Comment by Nolife999** [comment]
Closing issue for now. So to be clear, no refactor for that for now.
