### ISSUE TITLE
How to generate test report on github ?

### ISSUE THREAD

**Issue by Nolife999** [InseeFr/ARC#27]
We are asked to generate test reports. Any idea of what solution to implement Romain or HealerMikado ?
Also, is it possible to implement the integration gitlab-CI on Github the same way we does in our internal repository ?

**Comment by romaintailhurat** [comment]
I think i'll start from scratch with a simple Travis build and tests.

**Comment by Nolife999** [comment]
Nice. Thank you Romain

**Comment by romaintailhurat** [comment]
PR: https://github.com/InseeFr/ARC/pull/28

We need to adjust the test strategy in order to make the tests properly work on Travis.
