### ISSUE TITLE
Continuous integration tooling

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/ARC#3]
To expand the transparency on the project, i suggest to add at least :

- a build service (like Travis CI and such),
- a code quality tool (thinking here about Code climate for example).

**Comment by romaintailhurat** [comment]
Who should work on this issue ? @HealerMikado @Nolife999 or @romaintailhurat ?

**Comment by romaintailhurat** [comment]
CI is done, i'm working on code quality now.

Should we use [CodeClimate ](https://codeclimate.com/)or [SonarSource ](https://sonarcloud.io/about)?

**Comment by romaintailhurat** [comment]
For each, special permissions (admin i guess) on the ARC repo are needed. :grimacing:

**Comment by romaintailhurat** [comment]
We choose SonarCloud. To be set up.

**Comment by pierre-le-corre** [comment]
A basic CI is in place (mvn verify + sonar + docker).
