### ISSUE TITLE
Enhancing the Dockerfile for the webapp

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/ARC#4]
The existing [Docker images for ARC](https://github.com/InseeFr/ARC/blob/master/app.Dockerfile) is only handling the deployment of a pre-built WAR archive into a Tomcat application server.

Good practice nowadays is to include the build step into the image (a.k.a a build container) in order to have a unique and overarching build tool.

Ref :  https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Example : https://github.com/I3S-ESSnet/is2/blob/master/app.Dockerfile

**Comment by HealerMikado** [comment]
I made a first version of the new dockerfile. @romaintailhurat, could you review it ? ([update_dockerfile](https://github.com/InseeFr/ARC/tree/update_dockerfile))
As said in the #11 , the there is a problem with the log, but it should work

**Comment by romaintailhurat** [comment]
Seems good! Well done.

**Comment by HealerMikado** [comment]
Enhancing done in #14
