### ISSUE TITLE
Naming conventions for packages

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/ARC#5]
The package naming is a bit curious here : underscores ( _ ) could be replaced by dashes ( - ), and i also think that the base name should be "arc" instead of "arc_essnet".

**Comment by Nolife999** [comment]
Renaming to ARC

**Comment by Nolife999** [comment]
All packages had been renamed by replacing "arc_essnet" by "arc". Sub projects had been moved to new renamed folders.

**Comment by Nolife999** [comment]
Rename arc_utils to arc-utils and user_guide to user-guide

**Comment by Nolife999** [comment]
Waiting for validation

**Comment by romaintailhurat** [comment]
The week has ended i think we can close the issue now.

**Comment by Nolife999** [comment]
Looks good
