### ISSUE TITLE
ARC REST API

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/ARC#6]
Simply suggesting here the use of a dedicated REST API tool ([Jersey](https://jersey.github.io/) is a good start) instead of implementing it from scratch with the use of Servlets.

This way we will benefit from related technology, like JSON parsing and ser/deser.

**Comment by Nolife999** [comment]
Indeed it would be a good things to move to REST API. Tough, the response of some services can be a very large text streamed data file so I wondering if REST API is able to handle such response type.
I will try it.

**Comment by romaintailhurat** [comment]
Hi Manu

I was not directly justifying the use of a REST API in any case, just highlighting the need for proper tooling if we decide to go this way. 😁

**Comment by Nolife999** [comment]
No problem Romain. I think you are right :P

**Comment by Nolife999** [comment]
We have rest api for rules set and service execution. The data retrieval service is still a servlet
