### ISSUE TITLE
Errror on WAR deploy

### ISSUE THREAD

**Issue by francescoamato** [InseeFr/ARC#60]
Hi,
I'm trying to deploy the arc-web.war on Tomcat 8, but I get this error:

01-Oct-2020 08:51:13.287 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
 org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'gererFamilleNormeAction': Unsatisfied dependency expressed through field 'properties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'properties' defined in class path resource [applicationContext.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'logConfiguration' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	
Regards,
Francesco

**Comment by pierre-le-corre** [comment]
Hi, thanks for the notification. 
The bug should be fixed now. Can you confirm if it's okay on your side?

**Comment by francescoamato** [comment]
Now it's ok.
In the meantime I had solved  adding the line   <env.logSettings>fr/insee/config/log4j2.xml</env.logSettings>  in \arc-web\pom.xml.

Thanks,
Francesco
