### ISSUE TITLE
Error adding Control rule

### ISSUE THREAD

**Issue by francescoamato** [InseeFr/ARC#61]
hi,
when I try to add Control Rule, I get this error: 

org.postgresql.util.PSQLException: ERROR: date/time field value out of range: "31/12/2020"
  Hint: Perhaps you need a different "datestyle" setting.
  Position: 254

![immagine](https://user-images.githubusercontent.com/49312682/95173020-6d0ede80-07b8-11eb-8f70-1d8a07229211.png)

Francesco

**Comment by pierre-le-corre** [comment]
Hi, 
Could you give me more info on the control rule you are trying to create?

**Comment by Nolife999** [comment]
Hello. It looks like a database configuration problem Francesco. Could you please give me the result of the following query ?

select setting from pg_settings where name='DateStyle'

**Comment by Nolife999** [comment]
It should be fixed Francesco.
