### ISSUE TITLE
Translate to english

### ISSUE THREAD

**Issue by HealerMikado** [InseeFr/ARC#7]
There is a lot of french in the application (documentation or fields/variables/methods/classes name) which need to be translate in English.

**Comment by Nolife999** [comment]
Franck, could you please take care of the following modules in the package : ARC/arc-utils/src/main/java/fr/insee/arc/utils/ ?
batch
bdd
dao
files
format
Thank you

**Comment by Nolife999** [comment]
Franck, could you please take care of the follwing module in the package ARC/arc-utils/src/main/java/fr/insee/arc/utils/ ?
batch
bdd
dao
files
format
Thank you

**Comment by Nolife999** [comment]
Romain, could you please take care of the follwing module in the package ARC/arc-utils/src/main/java/fr/insee/arc/utils/ ?
ressourceUtils
sqlengine
structure
textUtils
utils
webutils
Thank you

**Comment by Nolife999** [comment]
Manuel, arc-core

**Comment by romaintailhurat** [comment]
There are still some french text parts in the POMs ; because those are mainly training guidelines, they can be removed.

**Comment by romaintailhurat** [comment]
In the [Token class](https://github.com/InseeFr/ARC/blob/master/arc-utils/src/main/java/fr/insee/arc/utils/sqlengine/Tokens.java), we store StringToken constants that are used by the engine to build expressions.

The form of a token is like:
```java
public static final IToken TOK_NOM_PHASE = new StringToken("tok_nom_phase");
```
It's easy to refactor the constant name (`TOK_NOM_PHASE` in this case), my IDE will work through all the renamings.

This is not the case for the string part (`"tok_nom_phase"`), and it is obviously not the case if this string exists somewhere else (not in the java code but in a DB trigger or a property).

Do you know if i can safely rename the string parts or if not, where are the dependencies ?

**Comment by romaintailhurat** [comment]
Hi there.

I'll resume my work on translating the code, and i still need an answer on my previous comment, please. :panda_face: :+1:

**Comment by romaintailhurat** [comment]
> Do you know if i can safely rename the string parts or if not, where are the dependencies ?

According to @Nolife999 it's okay, good to go. :ok_hand:

**Comment by romaintailhurat** [comment]
I'm don translating my part, maybe i can start working on translating part of the arc-core package ?
